language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - ruby-head-clang
  - jruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: jruby

branches:
  only:
  - gh-pages
