language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - ruby-head-clang
  - jruby

matrix:
  allow_failures:
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: jruby

branches:
  only:
  - gh-pages

script: bundle exec rake test
